import type { Criterion } from "$lib/types/index.js";

/**
 * All 137 trauma triage criteria, hardcoded from the medical team's reference CSV.
 *
 * Classification:
 *   - 20 deterministic (GCS, SBP, RR thresholds)
 *   - 2 hybrid (HR + qualitative perfusion)
 *   - 115 LLM-only (mechanism, injury, burn, procedural)
 *
 * VitalRules are defined inline for deterministic and hybrid criteria.
 */
export const CRITERIA: Criterion[] = [
  // ═══════════════════════════════════════════════════════════════════
  // ADULT — Level 1
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 1,
    description: "Glasgow coma score (GCS) < 12",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "<", threshold: 12 },
  },
  {
    id: 2,
    description: "Injury with associated tachycardia (Heart Rate (HR) > 100) AND poor perfusion",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "hybrid",
    vitalRule: {
      field: "hr",
      operator: ">",
      threshold: 100,
      requiresLlmConfirmation: "poor perfusion",
    },
  },
  {
    id: 3,
    description: "Systolic Blood Pressure (SBP) < 90",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 90 },
  },
  {
    id: 4,
    description: "Respiratory rate (RR) < 10",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "deterministic",
    vitalRule: { field: "rr", operator: "<", threshold: 10 },
  },
  {
    id: 5,
    description: "Respiratory rate (RR) > 29",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "deterministic",
    vitalRule: { field: "rr", operator: ">", threshold: 29 },
  },
  {
    id: 6,
    description: "Respiratory distress",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 7,
    description: "Intubated",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 8,
    description: "Flail chest",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 9,
    description:
      "Pleural decompression (needle decompression, chest tube placement, finger thoracostomy)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 10,
    description: "Penetrating injury to the head",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 11,
    description: "Penetrating injury or significant wound to the neck",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 12,
    description: "Penetrating injury to the torso (chest, back or abdomen)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 13,
    description:
      "Penetrating injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 14,
    description: "Penetrating injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 15,
    description: "Suspected or identified pelvic fracture",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 16,
    description: "Paralysis related to trauma",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 17,
    description: "Pulseless extremity (arm or leg)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 18,
    description:
      "Crush or degloving injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 19,
    description: "Mangled arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 20,
    description: "Crush or degloving injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 21,
    description: "Mangled leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 22,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns > 20% of total body surface area (TBSA)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 23,
    description: "Airway burns or concern for inhalational injury / burn",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 24,
    description:
      "Electrocution / electric shock with high voltage or greater than household current (> 120 volts)",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 25,
    description:
      "Blood product administration related to trauma - whole blood, packed red blood cells (RBC), fresh frozen plasma (FFP), platelets",
    activationLevel: "Level 1",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // ADULT — Level 2
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 26,
    description: "Glasgow coma scale (GCS) == 12 or 13",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "range", threshold: 12, thresholdHigh: 13 },
  },
  {
    id: 27,
    description: "Fall from > 15 feet height",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 28,
    description:
      "High speed (>= 55 mph) automobile crash AND suspected significant injuries (e.g., non-ambulatory)",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 29,
    description: "Motorcycle crash AND suspected significant injuries (e.g., non-ambulatory)",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 30,
    description:
      "Pedestrian hit by an automobile (automobile vs pedestrian) > 10 mph AND significant impact or suspected significant injuries",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 31,
    description:
      "Bicyclist hit by an automobile (automobile vs bicycle) > 10 mph AND significant impact or suspected significant injuries",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 32,
    description: "Active bleeding requiring a tourniquet or wound packing",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 33,
    description: "Poorly controlled bleeding despite pressure or bandaging",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 34,
    description: "More than one open fracture (excluding the hands or feet)",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 35,
    description:
      "More than one suspected long bone fracture (thigh, leg, arm, femur, humerus, tibia). This does not include hands or feet. This may be described as a deformity or shortening.",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 36,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns between 10% and 20% of total body surface area (TBSA)",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 37,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns to the face without suspected inhalation or airway injury.",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 38,
    description: "Pregnancy > 20 weeks gestational age AND abdominal or pelvic pain",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 39,
    description: "Pregnancy > 20 weeks gestational age AND vaginal bleeding",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 40,
    description: "Pregnancy > 20 weeks gestational age AND evidence of active labor",
    activationLevel: "Level 2",
    category: "Adult",
    ageRangeLabel: "16 - 64",
    ageMin: 16,
    ageMax: 64,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // ADULT — Level 3
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 41,
    description: "Ejection from an automobile",
    activationLevel: "Level 3",
    category: "Adult",
    ageRangeLabel: "18 - 64",
    ageMin: 18,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 42,
    description: "Moped crash with speed > 25 mph",
    activationLevel: "Level 3",
    category: "Adult",
    ageRangeLabel: "18 - 64",
    ageMin: 18,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 43,
    description: "Bicycle crash with speed > 25 mph",
    activationLevel: "Level 3",
    category: "Adult",
    ageRangeLabel: "18 - 64",
    ageMin: 18,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 44,
    description: "Death of another passenger in the SAME vehicle as the patient",
    activationLevel: "Level 3",
    category: "Adult",
    ageRangeLabel: "18 - 64",
    ageMin: 18,
    ageMax: 64,
    evaluationMethod: "llm",
  },
  {
    id: 45,
    description:
      "Pregnancy > 20 weeks gestational age WITHOUT abdominal pain, pelvic pain, vaginal bleeding or evidence of active labor",
    activationLevel: "Level 3",
    category: "Adult",
    ageRangeLabel: "18 - 64",
    ageMin: 18,
    ageMax: 64,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // PEDIATRIC — Level 1
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 46,
    description: "Glasgow coma score (GCS) < 12",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "<", threshold: 12 },
  },
  {
    id: 47,
    description: "Injury with associated tachycardia AND evidence of poor perfusion",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 48,
    description: "Systolic blood pressure (SBP) < 70 mmHg for age 0 - 12 months (<= 1 year)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 1,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 70 },
  },
  {
    id: 49,
    description: "Systolic blood pressure (SBP) < 74 mmHg for a 2 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 2,
    ageMax: 2,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 74 },
  },
  {
    id: 50,
    description: "Systolic blood pressure (SBP) < 76 mmHg for a 3 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 3,
    ageMax: 3,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 76 },
  },
  {
    id: 51,
    description: "Systolic blood pressure (SBP) < 78 mmHg for a 4 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 4,
    ageMax: 4,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 78 },
  },
  {
    id: 52,
    description: "Systolic blood pressure (SBP) < 80 mmHg for a 5 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 5,
    ageMax: 5,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 80 },
  },
  {
    id: 53,
    description: "Systolic blood pressure (SBP) < 82 mmHg for a 6 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 6,
    ageMax: 6,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 82 },
  },
  {
    id: 54,
    description: "Systolic blood pressure (SBP) < 84 mmHg for a 7 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 7,
    ageMax: 7,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 84 },
  },
  {
    id: 55,
    description: "Systolic blood pressure (SBP) < 86 mmHg for an 8 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 8,
    ageMax: 8,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 86 },
  },
  {
    id: 56,
    description: "Systolic blood pressure (SBP) < 88 mmHg for a 9 year old",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 9,
    ageMax: 9,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 88 },
  },
  {
    id: 57,
    description: "Systolic blood pressure (SBP) <= 90 for patients age 10 - 15",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 10,
    ageMax: 15,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<=", threshold: 90 },
  },
  {
    id: 58,
    description: "Respiratory distress",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 59,
    description: "Intubated - Endotracheal (ET) tube, Laryngeal mask airway (LMA, iGel)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 60,
    description: "Flail chest",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 61,
    description: "Pleural decompression (needle decompression, chest tube)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 62,
    description: "Penetrating injury to the head",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 63,
    description: "Penetrating injury or significant wound to the neck",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 64,
    description: "Penetrating injury to the torso (chest, back or abdomen)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 65,
    description:
      "Penetrating injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 66,
    description: "Penetrating injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 67,
    description: "Suspected or identified pelvic fracture",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 68,
    description: "Paralysis related to trauma",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 69,
    description: "Pulseless extremity (arm or leg)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 70,
    description:
      "Crush or degloving injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 71,
    description: "Mangled arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 72,
    description: "Crush or degloving injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 73,
    description: "Mangled leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 74,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns > 20% of total body surface area (TBSA)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 75,
    description: "Airway burns or concern for inhalational injury / burn",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 76,
    description:
      "Electrocution / electric shock with high voltage or greater than household current (> 120 volts)",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 77,
    description:
      "Blood product administration related to trauma - whole blood, packed red blood cells (RBC), fresh frozen plasma (FFP), platelets",
    activationLevel: "Level 1",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // PEDIATRIC — Level 2
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 78,
    description: "Glasgow coma score (GCS) = 12 or 13",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "range", threshold: 12, thresholdHigh: 13 },
  },
  {
    id: 79,
    description: "Fall from > 5 feet height (consider height of object)",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 80,
    description: "High speed (>= 55 mph) automobile crash AND significant vehicle damage",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 81,
    description: "Motorcycle crash (MCC) with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 82,
    description: "ATV crash with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 83,
    description: "Moped crash with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 84,
    description: "Golf cart crash with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 85,
    description: "Go cart crash with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 86,
    description: "Pedestrian hit by an automobile (auto vs pedestrian) with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 87,
    description: "Bicyclist hit by an automobile (auto vs bicycle) with significant impact",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 88,
    description: "Active bleeding requiring a tourniquet or wound packing",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 89,
    description: "Poorly controlled bleeding despite pressure or bandaging",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 90,
    description: "More than one open fracture (excluding the hands or feet)",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 91,
    description:
      "More than one suspected long bone fracture (thigh, leg, arm, femur, humerus, tibia). This does not include hands or feet.",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 92,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns between 10% and 20% of total body surface area (TBSA)",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 93,
    description:
      "Full or partial thickness burns to the face without suspected inhalation or airway injury.",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },
  {
    id: 94,
    description: "Significant neurological deficit (extremity numbness)",
    activationLevel: "Level 2",
    category: "Pediatric",
    ageRangeLabel: "0 - 15",
    ageMin: 0,
    ageMax: 15,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // PEDIATRIC — Level 3
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 95,
    description: "Ejection from an automobile",
    activationLevel: "Level 3",
    category: "Pediatric",
    ageRangeLabel: "0 - 17",
    ageMin: 0,
    ageMax: 17,
    evaluationMethod: "llm",
  },
  {
    id: 96,
    description:
      "Seatbelt sign (bruising or wounds over the abdomen or chest caused by a seatbelt)",
    activationLevel: "Level 3",
    category: "Pediatric",
    ageRangeLabel: "0 - 17",
    ageMin: 0,
    ageMax: 17,
    evaluationMethod: "llm",
  },
  {
    id: 97,
    description:
      "Potential handlebar injury (injury to the abdomen caused by the handlebar during a bicycle accident)",
    activationLevel: "Level 3",
    category: "Pediatric",
    ageRangeLabel: "0 - 17",
    ageMin: 0,
    ageMax: 17,
    evaluationMethod: "llm",
  },
  {
    id: 98,
    description: "Death of another passenger in the SAME vehicle as the patient",
    activationLevel: "Level 3",
    category: "Pediatric",
    ageRangeLabel: "0 - 17",
    ageMin: 0,
    ageMax: 17,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GERIATRIC — Level 1
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 99,
    description: "Glasgow coma score (GCS) < 12",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "<", threshold: 12 },
  },
  {
    id: 100,
    description: "Injury with associated tachycardia (Heart Rate (HR) > 90) AND poor perfusion",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "hybrid",
    vitalRule: {
      field: "hr",
      operator: ">",
      threshold: 90,
      requiresLlmConfirmation: "poor perfusion",
    },
  },
  {
    id: 101,
    description: "Systolic blood pressure (SBP) < 110",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "deterministic",
    vitalRule: { field: "sbp", operator: "<", threshold: 110 },
  },
  {
    id: 102,
    description: "Respiratory distress",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 103,
    description: "Intubated - Endotracheal (ET) tube, Laryngeal mask airway (LMA, iGel)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 104,
    description: "Flail chest",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 105,
    description: "Pleural decompression (needle decompression, chest tube)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 106,
    description: "Penetrating injury to the head",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 107,
    description: "Penetrating injury or significant wound to the neck",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 108,
    description: "Penetrating injury to the torso (chest, back or abdomen)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 109,
    description:
      "Penetrating injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 110,
    description: "Penetrating injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 111,
    description: "Suspected or identified pelvic fracture",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 112,
    description: "Paralysis related to trauma",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 113,
    description: "Pulseless extremity (arm or leg)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 114,
    description:
      "Crush or degloving injury to the arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 115,
    description: "Mangled arm proximal to the elbow (shoulder, axilla, bicep or tricep)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 116,
    description: "Crush or degloving injury to the leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 117,
    description: "Mangled leg proximal to the knee (groin or thigh)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 118,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns > 20% of total body surface area (TBSA)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 119,
    description: "Airway burns or concern for inhalational injury / burn",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 120,
    description:
      "Electrocution / electric shock with high voltage or greater than household current (> 120 volts)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 121,
    description:
      "Blood product administration related to trauma - whole blood, packed red blood cells (RBC), fresh frozen plasma (FFP), platelets",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 122,
    description: "Falls > 5 feet (non-ground level)",
    activationLevel: "Level 1",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GERIATRIC — Level 2
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 123,
    description: "Glasgow coma score (GCS) = 12 or 13",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "deterministic",
    vitalRule: { field: "gcs", operator: "range", threshold: 12, thresholdHigh: 13 },
  },
  {
    id: 124,
    description:
      "High speed (>= 55 mph) automobile crash AND suspected significant injuries (e.g., non-ambulatory)",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 125,
    description: "Motorcycle crash AND suspected significant injuries (e.g., non-ambulatory)",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 126,
    description:
      "Pedestrian hit by an automobile (automobile vs pedestrian) > 10 mph AND significant impact or suspected significant injuries",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 127,
    description:
      "Bicyclist hit by an automobile (automobile vs bicycle) > 10 mph AND significant impact or suspected significant injuries",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 128,
    description: "Active bleeding requiring a tourniquet or wound packing",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 129,
    description: "Poorly controlled bleeding despite pressure or bandaging",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 130,
    description: "More than one open fracture (excluding the hands or feet)",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 131,
    description:
      "More than one suspected long bone fracture (thigh, leg, arm, femur, humerus, tibia). This does not include hands or feet.",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 132,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns between 10% and 20% of total body surface area (TBSA)",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 133,
    description:
      "Full or partial thickness (2nd or 3rd degree) burns to the face without suspected inhalation or airway injury.",
    activationLevel: "Level 2",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },

  // ═══════════════════════════════════════════════════════════════════
  // GERIATRIC — Level 3
  // ═══════════════════════════════════════════════════════════════════
  {
    id: 134,
    description: "Ejection from an automobile",
    activationLevel: "Level 3",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 135,
    description: "Bicycle crash with speed > 25 mph",
    activationLevel: "Level 3",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 136,
    description: "Moped crash with speed > 25 mph",
    activationLevel: "Level 3",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
  {
    id: 137,
    description: "Death of another passenger in the SAME vehicle as the patient",
    activationLevel: "Level 3",
    category: "Geriatric",
    ageRangeLabel: "> 64",
    ageMin: 65,
    ageMax: null,
    evaluationMethod: "llm",
  },
];

/** O(1) lookup map keyed by criterion ID */
export const CRITERIA_MAP: Map<number, Criterion> = new Map(CRITERIA.map((c) => [c.id, c]));
